### ISSUE TITLE
Support Terminus v1.0

### ISSUE THREAD

**Issue by ccharlton** [pantheon-systems/terminus_debugging_tools#4]
Is this plugin superseded by other Terminus plugins? If not, are there changes needed to this to support Terminus v1.0?

**Comment by ttrowell** [comment]
+1 Would love 1.0 Support

**Comment by uberhacker** [comment]
@alexdicianu: This would be a nice upgrade considering there have been several users with database related issues as of late.

**Comment by alexdicianu** [comment]
Yep, I agree. I was still on the old terminus up until a few weeks ago :(

**Comment by alexdicianu** [comment]
Updated to support the new terminus v1.0.
